title: M. S. B

description: >
  Geotechnical Engineering Design,
  Numerical Modeling,
  Software, Data Science and AI Projects


url: "https://msaeedbabaee.github.io"


markdown: kramdown


collections:

  projects:
    output: true
    permalink: /projects/:name/


  services:
    output: true
    permalink: /services/:name/


plugins:
  - jekyll-feed



defaults:

  - scope:
      path: ""
      type: projects
    values:
      layout: project


  - scope:
      path: ""
      type: services
    values:
      layout: service
