
title: Your Name

description: >
  Geotechnical Engineering Design,
  Software Development,
  Data Science and AI Projects


url: "https://USERNAME.github.io"


markdown: kramdown


collections:

  projects:
    output: true
    permalink: /projects/:name/


  services:
    output: true
    permalink: /services/:name/


plugins:
  - jekyll-feed



defaults:

- scope:
    path: ""
    type: projects
  values:
    layout: project


- scope:
    path: ""
    type: services
  values:
    layout: service
